package:
  name: ruby
  version: 2.2.2

build:
  number: 0

source:
  fn: ruby-2.2.2.tar.gz
  url: http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.gz
  md5: 326e99ddc75381c7b50c85f7089f3260

test:
  commands:
    - ruby --version
    - ruby -e 'puts "Hi, from Ruby!"'
    - ruby -e 'require "rubygems"'
    - gem --version

requirements:
  build:
    - python
    - yaml
    - openssl 1.0.1g
    - zlib
  run:
    - python
    - zlib

about:
  home: https://www.ruby-lang.org/
  license: BSD
